autocommit on change

diff --git a/scripts2/autoreconf b/scripts2/autoreconf
--- a/scripts2/autoreconf
+++ b/scripts2/autoreconf
@@ -20,27 +20,19 @@
 
 . config/options $1
 
-if [ ! -z "$1" ]; then
-  printf "%${BUILD_INDENT}c ${boldred}CLEAN${endcolor}    $1\n" ' '>&$SILENT_OUT
+if [ ! -f "$PKG_BUILD/configure.in" \
+    -a ! -f "$PKG_BUILD/configure.ac" ] ; then
+  echo "configure.in or configure.ac not found"
+  exit 1
+fi
+
+if [ ! -f $PKG_BUILD/.autoreconf-done ] ; then
+  touch $PKG_BUILD/NEWS $PKG_BUILD/AUTHORS $PKG_BUILD/ChangeLog
+  mkdir -p $PKG_BUILD/m4
+
+  printf "%${BUILD_INDENT}c ${boldmagenta}AUTORECONF${endcolor}   $1\n" ' '>&$SILENT_OUT
   export BUILD_INDENT=$((${BUILD_INDENT:-1}+$BUILD_INDENT_SIZE))
 
-  if [ "$CLEAN_SOURCES" = true ]; then
-    rm -rf $SOURCES/$1
-    return
-  fi
-
-  for i in $BUILD/$1-*; do
-    if [ -d $i -a -f "$i/.openelec-unpack" ] ; then
-      . "$i/.openelec-unpack"
-      if [ "$STAMP_PKG_NAME" = "$1" ]; then
-        printf "%${BUILD_INDENT}c ${boldred}*${endcolor} ${red}Removing $i ...${endcolor}\n" ' '>&$SILENT_OUT
-        rm -rf $i
-      fi
-    else
-      # force clean if no stamp found (previous unpack failed)
-      printf "%${BUILD_INDENT}c * Removing $i ...\n" ' '>&$SILENT_OUT
-      rm -rf $i
-    fi
-  done
-  rm -f $STAMPS/$1/build_*
+  do_autoreconf $PKG_BUILD
+  touch $PKG_BUILD/.autoreconf-done
 fi
