autocommit on change

diff --git a/config/functions b/config/functions
--- a/config/functions
+++ b/config/functions
@@ -1,4 +1,43 @@
 setup_toolchain() {
+  # lto flag
+  if flag_enabled "lto" "$LTO_SUPPORT" "only-disable"; then
+    TARGET_CFLAGS+=" $CFLAGS_OPTIM_LTO"
+    TARGET_CXXFLAGS+=" $CXXFLAGS_OPTIM_LTO"
+    TARGET_LDFLAGS+=" $LDFLAGS_OPTIM_LTO"
+  fi
+
+  # gold flag
+  if flag_enabled "gold" "$GOLD_SUPPORT" "only-disable"; then
+    TARGET_LDFLAGS+=" $LDFLAGS_OPTIM_GOLD"
+  fi
+
+  # position-independent code
+  if flag_enabled "pic" "no"; then
+    TARGET_CFLAGS+=" $CFLAGS_OPTIM_PIC"
+    TARGET_CXXFLAGS+=" $CXXFLAGS_OPTIM_PIC"
+    TARGET_LDFLAGS+=" $LDFLAGS_OPTIM_PIC"
+  fi
+  if flag_enabled "pic:host" "no"; then
+    HOST_CFLAGS+=" $CFLAGS_OPTIM_PIC"
+    HOST_CXXFLAGS+=" $CXXFLAGS_OPTIM_PIC"
+    HOST_LDFLAGS+=" $LDFLAGS_OPTIM_PIC"
+  fi
+
+  # hardening support
+  if flag_enabled "hardening" "$HARDENING_SUPPORT"; then
+    TARGET_CFLAGS+=" $CFLAGS_OPTIM_HARDENING"
+    TARGET_CXXFLAGS+=" $CXXFLAGS_OPTIM_HARDENING"
+    TARGET_CFLAGS+=" $CPPFLAGS_OPTIM_HARDENING"
+    TARGET_LDFLAGS+=" $LDFLAGS_OPTIM_HARDENING"
+  fi
+
+  # parallel
+  if ! flag_enabled "parallel" "yes"; then
+    NINJA_OPTS="$NINJA_OPTS -j1"
+    export MAKEFLAGS="-j1"
+  else
+    export MAKEFLAGS="-j$CONCURRENCY_MAKE_LEVEL"
+  fi
   case "$1" in
     target|init)
       export DESTIMAGE="target"
@@ -318,6 +357,37 @@ listremoveitem() {
   echo "${tmp_array[@]}"
 }
 
+# check if a flag is enabled
+# $1: flag-name, $2: default (yes/no), $3: ingenious check (none,only-disable,only-enable)
+# set variable PKG_[FLAG]_[HOST/TARGET]_ENABLED=(yes/no)
+# return 0 if flag is enabled, otherwise 1
+flag_enabled() {
+  # make flag name upper case and replace hyphen with underscore, to use as variable name
+  local flag_name=${1^^}
+  [[ $flag_name =~ : ]] || flag_name+="_TARGET"
+  flag_name="PKG_${flag_name//[:-]/_}_ENABLED"
+
+  # check flag
+  if [ -n "${PKG_BUILD_FLAGS}" ] && listcontains "${PKG_BUILD_FLAGS}" "[+]?$1"; then
+    if [ "${3:none}" = "only-disable" ]; then
+      echo "ERROR: $1 can not enable via PKG_BUILD_FLAGS (found in $PKG_NAME)"
+      exit 1
+    fi
+    declare ${flag_name}="yes"
+    return 0
+  elif [ "$2" = "yes" ] && ! listcontains "${PKG_BUILD_FLAGS}" "-$1"; then
+    declare ${flag_name}="yes"
+    return 0
+  else
+    if [ "${3:none}" = "only-enable" ]; then
+      echo "ERROR: $1 can not disable via PKG_BUILD_FLAGS (found in $PKG_NAME)"
+      exit 1
+    fi
+    declare ${flag_name}="no"
+    return 1
+  fi
+}
+
 target_has_feature() {
   listcontains "$TARGET_FEATURES" "$1"
 }
@@ -561,7 +631,7 @@ install_driver_addon_files() {
   mkdir -p $PKG_MODULE_DIR
   find $@ -name \*.ko -exec cp {} $PKG_MODULE_DIR \;
 
-  find $PKG_MODULE_DIR -name \*.ko -exec $STRIP --strip-debug {} \;
+  find $PKG_MODULE_DIR -name \*.ko -exec ${TARGET_KERNEL_PREFIX}strip --strip-debug {} \;
 
   mkdir -p $PKG_ADDON_DIR
   cp $PKG_DIR/changelog.txt $PKG_ADDON_DIR
@@ -661,26 +731,6 @@ do_autoreconf() {
   fi
 }
 
-strip_lto() {
-  # strip out LTO optimization from *FLAGS
-  if [ -n "$GCC_OPTIM_LTO" ] ; then
-    CFLAGS=`echo $CFLAGS | sed -e "s|$GCC_OPTIM_LTO||g"`
-    CXXFLAGS=`echo $CXXFLAGS | sed -e "s|$GCC_OPTIM_LTO||g"`
-    TARGET_CFLAGS=`echo $TARGET_CFLAGS | sed -e "s|$GCC_OPTIM_LTO||g"`
-    TARGET_CXXFLAGS=`echo $TARGET_CXXFLAGS | sed -e "s|$GCC_OPTIM_LTO||g"`
-  fi
-  if [ -n "$LD_OPTIM_LTO" ] ; then
-    LDFLAGS=`echo $LDFLAGS | sed -e "s|$LD_OPTIM_LTO||g"`
-    TARGET_LDFLAGS=`echo $TARGET_LDFLAGS | sed -e "s|$LD_OPTIM_LTO||g"`
-  fi
-}
-
-strip_gold() {
-  # strip out usage from GOLD linker
-  LDFLAGS=`echo $LDFLAGS | sed -e "s|-fuse-ld=gold||g"`
-  TARGET_LDFLAGS=`echo $TARGET_LDFLAGS | sed -e "s|-fuse-ld=gold||g"`
-}
-
 strip_hard() {
   CFLAGS=`echo $CFLAGS | sed -e "s|-fno-plt||g"`
   TARGET_CFLAGS=`echo $TARGET_CFLAGS | sed -e "s|-fno-plt||g"`
@@ -770,6 +820,23 @@ check_path() {
     echo -e $check_pathmessage
     exit 1
   fi
+}
+
+load_build_config() {
+  if [ -d "${1}" -a -f ${1}/.build.conf ]; then
+    source ${1}/.build.conf
+    return 0
+  fi
+  return 1
+}
+
+save_build_config() {
+  local var
+  mkdir -p ${BUILD}
+  rm -f ${BUILD}/.build.conf
+  for var in PROJECT DEVICE ARCH DEBUG BUILD_SUFFIX; do
+    echo "export ${var}=\"${!var}\"" >> ${BUILD}/.build.conf
+  done
 }
 
 check_config() {
