autocommit on change

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -6,6 +6,20 @@
 # Copyright (C) 2009-2014 Stephan Raue (stephan@openelec.tv)
 # Copyright (C) 2016-present Team LibreELEC (https://libreelec.tv)
 
+# create directories
+/usr/bin/busybox mkdir -p /dev
+/usr/bin/busybox mkdir -p /proc
+/usr/bin/busybox mkdir -p /sys
+/usr/bin/busybox mkdir -p /tmp
+/usr/bin/busybox mkdir -p /flash
+/usr/bin/busybox mkdir -p /sysroot
+/usr/bin/busybox mkdir -p /storage
+
+# mount all needed special filesystems
+/usr/bin/busybox mount -t devtmpfs devtmpfs /dev
+/usr/bin/busybox mount -t proc proc /proc
+/usr/bin/busybox mount -t sysfs sysfs /sys
+
 # set needed variables
 MODULE_DIR=/usr/lib/modules
 
@@ -39,7 +53,7 @@ MACHINE_UID="$(cat /proc/cpuinfo | awk '/^Serial/{s=$3; gsub ("^0*","",s); print
 [ -z "$MACHINE_UID" ] && MACHINE_UID="$(cat /sys/class/net/eth0/address 2>/dev/null | tr -d :)"
 
 # common functions
-. /usr/lib/functions
+. /functions
 
 # script functions
 progress() {
@@ -343,6 +357,85 @@ update_bootloader() {
   umount /sysroot
 }
 
+load_modules() {
+  progress "Loading kernel modules"
+
+  [ ! -f "/etc/modules" ] && return
+  for module in $(cat /etc/modules); do
+    progress "Loading kernel module $module"
+    insmod "$MODULE_DIR/$module.ko" || progress "... Failed to load kernel module $module, skipping"
+  done
+}
+
+load_splash() {
+  local set_default_res=no
+  local vres
+
+  if [ ! "$SPLASH" = "no" ]; then
+    progress "Loading bootsplash"
+
+    # load uvesafb module if needed
+    if [ -f "$MODULE_DIR/uvesafb.ko" -a ! -e /dev/fb0 ]; then
+      progress "Loading kernel module uvesafb.ko"
+      insmod "$MODULE_DIR/uvesafb.ko" && set_default_res=yes || progress "... Failed to load kernel module uvesafb, skipping"
+    fi
+
+    if [ -e /dev/fb0 ]; then
+      # Set framebuffer to a custom resolution and/or fallback to default resolution (1024x768-32), if required.
+      if [ ! "$SWITCH_FRAMEBUFFER" = "no" ]; then
+        if [ "$SWITCH_FRAMEBUFFER" = "1080" ]; then
+          SWITCH_FRAMEBUFFER="1920 1080 1920 1080 32"
+        elif [ "$SWITCH_FRAMEBUFFER" = "720" ]; then
+          SWITCH_FRAMEBUFFER="1280 720 1280 720 32"
+        fi
+
+        # Try setting a custom framebuffer resolution
+        if [ ! "${SWITCH_FRAMEBUFFER:-yes}" = "yes" ]; then
+          fbset -g $SWITCH_FRAMEBUFFER 2>/dev/null && set_default_res=no
+        fi
+
+        # Set a default resolution if required
+        if [ "$set_default_res" = "yes" ]; then
+          fbset -g 1024 768 1024 768 32
+        fi
+      fi
+
+      # load splash
+      if [ -f /splash/splash.conf ]; then
+        . /splash/splash.conf
+      fi
+
+      # Select splash image based on current native resolution
+      if [ -z "$SPLASHIMAGE" ]; then
+        vres="$(fbset 2>/dev/null | awk '/geometry/ { print $3 }')"
+
+        if [ -f /flash/oemsplash.png -o -f /flash/oemsplash-1080.png ]; then
+          if [ -n "$vres" -a -f /flash/oemsplash-$vres.png ]; then
+            SPLASHIMAGE="/flash/oemsplash-$vres.png"
+          elif [ -f /flash/oemsplash-1080.png ]; then
+            SPLASHIMAGE="/flash/oemsplash-1080.png"
+          else
+            SPLASHIMAGE="/flash/oemsplash.png"
+          fi
+        else
+          if [ -n "$vres" -a -f /splash/splash-$vres.png ]; then
+            SPLASHIMAGE="/splash/splash-$vres.png"
+          else
+            SPLASHIMAGE="/splash/splash-1080.png"
+          fi
+        fi
+      fi
+
+      if [ -n "$SPLASHIMAGE" -a -f "$SPLASHIMAGE" ]; then
+        ply-image $SPLASHIMAGE > /dev/null 2>&1
+      fi
+
+      debug_msg "Framebuffer vertical res: $vres"
+      debug_msg "Framebuffer splash image: $SPLASHIMAGE"
+    fi
+  fi
+}
+
 do_reboot() {
   echo "System reboots now..."
 
@@ -394,6 +487,30 @@ force_fsck() {
   fi
 }
 
+check_disks() {
+  if [ "$RUN_FSCK" = "yes" -a -n "$RUN_FSCK_DISKS" ]; then
+    progress "Checking disk(s): $RUN_FSCK_DISKS"
+    /usr/sbin/fsck -T -M -p -a $RUN_FSCK_DISKS > /dev/null 2>&1
+    FSCK_RET=$?
+
+    # FSCK_RET is the bit-wise OR of the exit codes for each filesystem that is checked.
+    if [ $(( $FSCK_RET & 4 )) -eq 4 ]; then
+      # errors left
+      force_fsck
+    elif [ $(( $FSCK_RET & 2 )) -eq 2 ]; then
+      # reboot needed
+      echo "Filesystem repaired, reboot needed..."
+      do_reboot
+    elif [ $(( $FSCK_RET & 1 )) -eq 1 ]; then
+      # filesystem errors corrected
+      progress "Filesystem errors corrected , continuing..."
+    elif [ $(( $FSCK_RET & 0 )) -eq 0 ]; then
+      # no errors found
+      progress "No filesystem errors found, continuing..."
+    fi
+  fi
+}
+
 wakeonlan() {
   if [ "$STORAGE_NETBOOT" = "yes" ]; then
     wol_ip=${disk%:*}
@@ -418,14 +535,86 @@ wakeonlan() {
 mount_flash() {
   progress "Mounting flash"
 
+  wakeonlan
+
   mount_part "$boot" "/flash" "ro,noatime"
+
+  if [ -f /flash/post-flash.sh ]; then
+    . /flash/post-flash.sh
+  fi
 }
 
 mount_storage() {
   progress "Mounting storage"
 
-  # mount tmpfs and exit early. disk=xx is not allowed in live mode
-  mount -t tmpfs none /storage
+  if [ "$LIVE" = "yes" ]; then
+    # mount tmpfs and exit early. disk=xx is not allowed in live mode
+    mount -t tmpfs none /storage
+    return
+  fi
+
+  wakeonlan
+
+  if [ -n "$disk" ]; then
+    if [ -n "$OVERLAY" ]; then
+      OVERLAY_DIR=$(cat /sys/class/net/eth0/address | tr -d :)
+
+      mount_part "$disk" "/storage" "rw,noatime"
+      mkdir -p /storage/$OVERLAY_DIR
+      umount /storage
+
+      # split $disk into $target,$options so we can append $OVERLAY_DIR
+      options="${disk#*,}"
+      target="${disk%%,*}"
+      if [ "$options" = "$disk" ]; then
+        disk="$target/$OVERLAY_DIR"
+      else
+        disk="$target/$OVERLAY_DIR,$options"
+      fi
+    fi
+
+    if [ -f /flash/mount-storage.sh ]; then
+      . /flash/mount-storage.sh
+    else
+      mount_part "$disk" "/storage" "rw,noatime"
+    fi
+  else
+    # /storage should always be writable
+    mount -t tmpfs none /storage
+  fi
+}
+
+# Make last bootloader label (installer, live, run etc.) as the new default
+update_bootmenu() {
+  local crnt_default
+
+  if [ -n "$SYSLINUX_DEFAULT" -a -f /flash/syslinux.cfg ]; then
+    if grep -q "^LABEL $SYSLINUX_DEFAULT\$" /flash/syslinux.cfg; then
+      crnt_default="$(awk '/^DEFAULT/ {print $2}' /flash/syslinux.cfg)"
+      if [ ! "$crnt_default" = "$SYSLINUX_DEFAULT" ]; then
+        progress "Updating /flash/syslinux.cfg [$crnt_default -> $SYSLINUX_DEFAULT]"
+
+        mount -o remount,rw /flash
+        sed -i "s/^DEFAULT .*/DEFAULT $SYSLINUX_DEFAULT/" /flash/syslinux.cfg
+        rm -f /flash/EFI/BOOT/syslinux.cfg
+        mount -o remount,ro /flash
+      fi
+    fi
+  fi
+
+  if [ -n "$GRUB_DEFAULT" -a -f /flash/EFI/BOOT/grub.cfg ]; then
+    if grep -q "^menuentry \"$GRUB_DEFAULT\"" /flash/EFI/BOOT/grub.cfg; then
+      crnt_default="$(awk '/^set default/ {print substr($2,9,19)}' /flash/EFI/BOOT/grub.cfg)"
+      if [ ! "$crnt_default" = "\"$GRUB_DEFAULT\"" ]; then
+        progress "Updating /flash/EFI/BOOT/grub.cfg [$crnt_default -> \"$GRUB_DEFAULT\"]"
+
+        mount -o remount,rw /flash
+        sed -i "s/^set default=.*/set default=\"$GRUB_DEFAULT\"/" /flash/EFI/BOOT/grub.cfg
+        rm -f /flash/grub.cfg
+        mount -o remount,ro /flash
+      fi
+    fi
+  fi
 }
 
 check_out_of_space() {
@@ -471,6 +660,246 @@ do_cleanup() {
   StopProgress "done"
 }
 
+check_update() {
+  progress "Checking for updates"
+  UPDATE_TAR=$(ls -1 "$UPDATE_DIR"/*.tar 2>/dev/null | head -n 1)
+  UPDATE_IMG_GZ=$(ls -1 "$UPDATE_DIR"/*.img.gz 2>/dev/null | head -n 1)
+  UPDATE_IMG=$(ls -1 "$UPDATE_DIR"/*.img 2>/dev/null | head -n 1)
+
+  if ! [ -f "$UPDATE_DIR/$UPDATE_KERNEL" -a -f "$UPDATE_DIR/$UPDATE_SYSTEM" ] &&
+     ! [ -f "$UPDATE_TAR" -o -f "$UPDATE_IMG_GZ" -o -f "$UPDATE_IMG" ]; then
+    return 0
+  fi
+
+  if [ "$UPDATE_DISABLED" = "yes" ]; then
+    echo "Updating is not supported on netboot"
+    do_cleanup
+    StartProgress countdown "Normal startup in 10s... " 10 "NOW"
+    return 0
+  fi
+
+  if [ -d $UPDATE_DIR/.tmp ]; then
+    echo "Failed update detected - performing recovery."
+    echo ""
+    do_cleanup
+    StartProgress countdown "Normal startup in 10s... " 10 "NOW"
+    return 0
+  fi
+
+  mkdir -p $UPDATE_DIR/.tmp &>/dev/null
+  sync
+
+  echo "UPGRADE IN PROGRESS"
+  echo ""
+  echo "Please do not reboot or turn off your @DISTRONAME@ device!"
+  echo ""
+
+  if [ -f "$UPDATE_TAR" ]; then
+    TARRESULT="0"
+
+    echo "Found new .tar archive"
+    UPDATE_FILENAME="$UPDATE_TAR"
+    StartProgress spinner "Extracting contents of archive... "
+      tar -xf "$UPDATE_TAR" -C $UPDATE_DIR/.tmp 1>/dev/null 2>/tmp/tarresult.txt || TARRESULT="1"
+
+    if [ "${TARRESULT}" -eq "0" ]; then
+      mv $UPDATE_DIR/.tmp/*/target/* $UPDATE_DIR &>/dev/null
+      sync
+      StopProgress "done"
+    else
+      StopProgress "FAILED"
+
+      echo "Failed to extract contents of archive file!"
+      echo "tar result: '$(cat /tmp/tarresult.txt)'"
+
+      check_out_of_space "archive"
+
+      do_cleanup
+      StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+      return 0
+    fi
+  elif [ -f "$UPDATE_IMG_GZ" -o -f "$UPDATE_IMG" ]; then
+    mkdir -p $UPDATE_DIR/.tmp/mnt &>/dev/null
+    IMG_FILE="$UPDATE_DIR/.tmp/update.img"
+    GZRESULT="0"
+
+    if [ -f "$UPDATE_IMG_GZ" ]; then
+      echo "Found new compressed image file"
+      UPDATE_FILENAME="$UPDATE_IMG_GZ"
+      StartProgress spinner "Decompressing image file... "
+        gunzip -d -c "$UPDATE_IMG_GZ" 1>$IMG_FILE 2>/tmp/gzresult.txt || GZRESULT="1"
+        sync
+        [ "${GZRESULT}" -eq "0" ] && StopProgress "OK" || StopProgress "FAILED"
+
+      if [ "${GZRESULT}" -eq "1" ]; then
+        echo "Failed to decompress image file!"
+        echo "gunzip result: '$(cat /tmp/gzresult.txt)'"
+
+        check_out_of_space "compressed image"
+
+        do_cleanup
+        StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+        return 0
+      fi
+    else
+      echo "Found new image file"
+      UPDATE_FILENAME="$UPDATE_IMG"
+      mv "$UPDATE_IMG" $IMG_FILE
+    fi
+
+    LOOP=$(losetup -f)
+    LOOP_NUM=$(echo $LOOP | sed 's|/dev/loop||')
+    mknod $LOOP b 7 $LOOP_NUM &>/dev/null
+    losetup $LOOP $IMG_FILE
+
+    # check for MBR partititon
+    OFFSET=$(fdisk -u -l $LOOP 2>/dev/null | awk '/^[ ]*Device/{part=1; next}; part{if ($2 == "*") {print $5} else {print $4} ; exit}')
+    if [ -z "$OFFSET" ]; then
+      # check for GPT partititon
+      OFFSET=$(fdisk -u -l $LOOP 2>/dev/null | awk '/^Number/{part=1; next}; part{print $2; exit}')
+      if [ -z "$OFFSET" ]; then
+        echo "Could not find a valid system partition in image file!"
+        do_cleanup
+        StartProgress countdown "Normal startup in 10s... " 10 "NOW"
+        return 0
+      fi
+    fi
+
+    SECTOR_SIZE=$(cat /sys/devices/virtual/block/loop${LOOP_NUM}/queue/hw_sector_size)
+    losetup -d $LOOP
+    sync
+
+    OFFSET=$(($OFFSET * $SECTOR_SIZE))
+
+    # use losetup because busybox mount does not support the -o offset option
+    echo "Mounting system partition..."
+    losetup -o $OFFSET $LOOP $IMG_FILE
+    mount -o ro,loop $LOOP $UPDATE_DIR/.tmp/mnt
+
+    # don't make temporary files but instead copy
+    # directly from mountpoint to /flash
+    UPDATE_DIR=$UPDATE_ROOT/.tmp/mnt
+    UPDATE_KERNEL="@KERNEL_NAME@"
+  else
+    UPDATE_FILENAME="$UPDATE_DIR/$UPDATE_SYSTEM"
+  fi
+
+  sync
+
+  if [ ! -b "/$IMAGE_KERNEL" -a ! -f "/flash/$IMAGE_KERNEL" ] || [ ! -f "/flash/$IMAGE_SYSTEM" ]; then
+    echo "Missing (target) ${IMAGE_KERNEL} or ${IMAGE_SYSTEM}!"
+    do_cleanup
+    StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+    return 0
+  fi
+
+  if [ ! -f "$UPDATE_DIR/$UPDATE_KERNEL" -o ! -f "$UPDATE_DIR/$UPDATE_SYSTEM" ]; then
+    echo "Missing (source) ${UPDATE_KERNEL} or ${UPDATE_SYSTEM}!"
+    do_cleanup
+    StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+    return 0
+  fi
+
+  # check md5 sums if .nocheck doesn't exist
+  if [ ! -f "$UPDATE_ROOT/.nocheck" ]; then
+    if [ -f "$UPDATE_DIR/${UPDATE_KERNEL}.md5" -a -f "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" ]; then
+      # *.md5 size-check
+      if [ ! -s "$UPDATE_DIR/${UPDATE_KERNEL}.md5" -o ! -s "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" ]; then
+        echo "Zero-sized .md5 file!"
+        MD5_FAILED="1"
+      else
+        sed "s#target/KERNEL#$UPDATE_DIR/$UPDATE_KERNEL#g" "$UPDATE_DIR/${UPDATE_KERNEL}.md5" >"$UPDATE_ROOT/${UPDATE_KERNEL}.check.md5"
+        sed "s#target#$UPDATE_DIR#g" "$UPDATE_DIR/${UPDATE_SYSTEM}.md5" >"$UPDATE_ROOT/${UPDATE_SYSTEM}.check.md5"
+
+        StartProgress spinner "Checking ${UPDATE_KERNEL}.md5... "
+          if md5sum -sc "$UPDATE_ROOT/${UPDATE_KERNEL}.check.md5"; then
+            StopProgress "OK"
+          else
+            StopProgress "FAILED"
+            MD5_FAILED="1"
+          fi
+
+        StartProgress spinner "Checking ${UPDATE_SYSTEM}.md5... "
+          if md5sum -sc "$UPDATE_ROOT/${UPDATE_SYSTEM}.check.md5"; then
+            StopProgress "OK"
+          else
+            StopProgress "FAILED"
+            MD5_FAILED="1"
+          fi
+      fi
+    else
+      echo "Missing ${UPDATE_KERNEL}.md5 or ${UPDATE_SYSTEM}.md5!"
+      MD5_FAILED="1"
+    fi
+
+    if [ "$MD5_FAILED" -eq "1" ]; then
+      echo "md5 check failed!"
+      do_cleanup
+      StartProgress countdown "Normal startup in 30s... " 30 "NOW"
+      return 0
+    fi
+  fi
+
+  # Verify that the new upgrade is compatible with the current system - this should avoid creating
+  # non-booting systems after (for example) an RPi tar is incorrectly applied to an RPi2 system.
+  if [ ! -f "$UPDATE_ROOT/.nocompat" ]; then
+    if ! check_is_compatible "$UPDATE_FILENAME" "/flash/$IMAGE_SYSTEM" "$UPDATE_DIR/$UPDATE_SYSTEM"; then
+      do_cleanup
+      StartProgress countdown "Normal startup in 60s... " 60 "NOW"
+      return 0
+    fi
+  fi
+
+  # get sizes
+  FLASH_FREE=$(df /flash/ | awk '/[0-9]%/{print $4}')
+  FLASH_FREE=$(( $FLASH_FREE * 1024 ))
+
+  # Disregard kernel size if it's a a block device
+  if [ ! -b "/$IMAGE_KERNEL" ]; then
+    OLD_KERNEL=$(stat -t "/flash/$IMAGE_KERNEL" | awk '{print $2}')
+  else
+    OLD_KERNEL="0"
+  fi
+
+  OLD_SYSTEM=$(stat -t "/flash/$IMAGE_SYSTEM" | awk '{print $2}')
+  NEW_KERNEL=$(stat -t "$UPDATE_DIR/$UPDATE_KERNEL" | awk '{print $2}')
+  NEW_SYSTEM=$(stat -t "$UPDATE_DIR/$UPDATE_SYSTEM" | awk '{print $2}')
+
+  # old KERNEL+SYSTEM+free space - new KERNEL+SYSTEM must be higher than 5MB
+  # at least 5MB free after update
+
+  TMP_SIZE=$((OLD_KERNEL + OLD_SYSTEM + FLASH_FREE - NEW_KERNEL - NEW_SYSTEM))
+  FLASH_FREE_MIN=$((FLASH_FREE_MIN * 1024 * 1024))
+
+  if [ $TMP_SIZE -ge $FLASH_FREE_MIN ]; then
+    echo "Checking size: OK"
+  else
+    echo "Checking size: FAILED"
+    echo ""
+    echo "Your System (FAT) partition is too small for this update,"
+    echo "and there is not enough space for the update to be installed!"
+    echo ""
+    echo "You must re-install your system using the disk image of a"
+    echo "current release, or you must re-size your existing partitions"
+    echo "so that the System (FAT) partition is at least 512MB in size."
+    echo ""
+    do_cleanup
+    StartProgress countdown "Normal startup in 60s... " 60 "NOW"
+    return 0
+  fi
+
+  # all ok, update
+  if [ -b "/$IMAGE_KERNEL" ]; then
+    update_partition "Kernel" "$UPDATE_KERNEL" "/$IMAGE_KERNEL"
+  else
+    update_file "Kernel" "$UPDATE_KERNEL" "/flash/$IMAGE_KERNEL"
+  fi
+  update_file "System" "$UPDATE_SYSTEM" "/flash/$IMAGE_SYSTEM"
+  update_bootloader
+  do_cleanup
+  do_reboot
+}
+
 prepare_sysroot() {
   progress "Preparing system"
 
@@ -480,6 +909,9 @@ prepare_sysroot() {
     cp /flash/$IMAGE_SYSTEM /dev/$IMAGE_SYSTEM
     mount_part "/dev/$IMAGE_SYSTEM" "/sysroot" "ro,loop"
   fi
+
+  mount --move /flash /sysroot/flash
+  mount --move /storage /sysroot/storage
 
   if [ ! -d "/sysroot/usr/lib/kernel-overlays/base/lib/modules/$(uname -r)/" -a -f "/sysroot/usr/lib/systemd/systemd" ]; then
     echo ""
@@ -511,6 +943,10 @@ fi
 if [ -f "./platform_init" ]; then
   ./platform_init
 fi
+
+# clear screen and hide cursor
+clear
+hidecursor
 
 # parse command line arguments
 for arg in $(cat /proc/cmdline); do
@@ -624,8 +1060,68 @@ debug_msg "Unique identifier for this client: ${MACHINE_UID:-NOT AVAILABLE}"
 
 # main boot sequence
 for BOOT_STEP in \
+    load_modules \
+    check_disks \
     mount_flash \
+    update_bootmenu \
+    load_splash \
+    mount_storage \
+    check_update \
     prepare_sysroot; do
   $BOOT_STEP
   [ -n "$DEBUG" ] && break_after $BOOT_STEP
 done
+
+BOOT_STEP=final
+
+# log if booting from usb / removable storage
+STORAGE=$(cat /proc/mounts | grep " /sysroot/storage " | awk '{print $1}' | awk -F '/' '{print $3}')
+FLASH=$(cat /proc/mounts | grep " /sysroot/flash " | awk '{print $1}' | awk -F '/' '{print $3}')
+for i in $STORAGE $FLASH ; do
+  if [ -n "$i" ]; then
+    removable="/sys/class/block/*/$i/../removable"
+    if [ -e $removable ]; then
+      if [ "$(cat $removable 2>/dev/null)" = "1" ]; then
+        echo "### BIG FAT WARNING" > /dev/kmsg
+        echo "### $i is removable. suspend/resume may not work" > /dev/kmsg
+      fi
+    fi
+  fi
+done
+# move some special filesystems
+/usr/bin/busybox mount --move /dev /sysroot/dev
+/usr/bin/busybox mount --move /proc /sysroot/proc
+/usr/bin/busybox mount --move /sys /sysroot/sys
+/usr/bin/busybox rm -fr /tmp
+
+# tell OE settings addon to disable updates
+if [ "$UPDATE_DISABLED" = "yes" ]; then
+  echo "" > /sysroot/dev/.update_disabled
+fi
+
+if [ "$FLASH_NETBOOT" = "yes" ]; then
+  echo "" > /sysroot/dev/.flash_netboot
+fi
+
+# swap can not be used over nfs.(see scripts/mount-swap)
+if [ "$STORAGE_NETBOOT" = "yes" ]; then
+  echo "" > /sysroot/dev/.storage_netboot
+fi
+
+if [ -f /sysroot/storage/.please_resize_me ]; then
+  INIT_UNIT="--unit=fs-resize.target"
+fi
+
+BACKUP_FILE=$(ls -1 /sysroot/storage/.restore/??????????????.tar 2>/dev/null | head -n 1)
+if [ -f "$BACKUP_FILE" ]; then
+  INIT_UNIT="--unit=backup-restore.target"
+fi
+
+if [ -f /sysroot/storage/.cache/reset_oe -o -f /sysroot/storage/.cache/reset_xbmc ]; then
+  INIT_UNIT="--unit=factory-reset.target"
+fi
+
+# switch to new sysroot and start real init
+exec /usr/bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS $INIT_UNIT
+
+error "switch_root" "Error in initramfs. Could not switch to new root"
