autocommit on change

diff --git a/packages/sysutils/busybox/scripts/init b/packages/sysutils/busybox/scripts/init
--- a/packages/sysutils/busybox/scripts/init
+++ b/packages/sysutils/busybox/scripts/init
@@ -690,7 +690,7 @@
     mount --move /flash /sysroot/flash
     mount --move /storage /sysroot/storage
 
-    if [ ! -d "/sysroot/lib/modules/$(uname -r)/" -a -f "/sysroot/$SYSTEMD_BIN" ]; then
+    if [ ! -d "/sysroot/lib/modules/$(uname -r)/" -a -f "/sysroot/usr/lib/systemd/systemd" ]; then
       if [ -e /dev/psplash_fifo ] ; then
         echo "QUIT" > /dev/psplash_fifo
       fi
@@ -705,7 +705,7 @@
     fi
 
 
-    [ -f "/sysroot/$SYSTEMD_BIN" ] || error "final_check" "Could not find system."
+    [ -f "/sysroot/usr/lib/systemd/systemd" ] || error "final_check" "Could not find system."
   }
 
   if [ "${boot%%=*}" = "FILE" ]; then
@@ -768,6 +768,6 @@
     INIT_UNIT="--unit=factory-reset.target"
   fi
   # switch to new sysroot and start real init
-  exec /bin/busybox switch_root /sysroot $SYSTEMD_BIN $INIT_ARGS $INIT_UNIT
+  exec /bin/busybox switch_root /sysroot /usr/lib/systemd/systemd $INIT_ARGS $INIT_UNIT
 
   error "switch_root" "Error in initramfs. Could not switch to new root"
