autocommit on change

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -85,34 +85,7 @@ else
   build_msg "CLR_BUILD" "BUILD" "${PKG_NAME} $(print_color "CLR_TARGET" "(${TARGET})")" "indent"
 fi
 
-# setup configure scripts
-PKG_CONFIGURE_SCRIPT="${PKG_CONFIGURE_SCRIPT:-${PKG_BUILD}/configure}"
-PKG_CMAKE_SCRIPT="${PKG_CMAKE_SCRIPT:-${PKG_BUILD}/CMakeLists.txt}"
-PKG_MESON_SCRIPT="${PKG_MESON_SCRIPT:-${PKG_BUILD}/meson.build}"
-
-# auto detect toolchain
-_auto_toolchain=""
-if [ -z "${PKG_TOOLCHAIN}" -o "${PKG_TOOLCHAIN}" = "auto" ]; then
-  if [ -f "${PKG_MESON_SCRIPT}" ]; then
-    PKG_TOOLCHAIN="meson"
-  elif [ -f "${PKG_CMAKE_SCRIPT}" ]; then
-    PKG_TOOLCHAIN="cmake"
-  elif [ -f "${PKG_CONFIGURE_SCRIPT}" ]; then
-    PKG_TOOLCHAIN="configure"
-  elif [ -f "${PKG_BUILD}/Makefile" ]; then
-    PKG_TOOLCHAIN="make"
-  else
-    die "Not possible to detect toolchain automatically. Add PKG_TOOLCHAIN= to package.mk"
-  fi
-  _auto_toolchain=" (auto-detect)"
-fi
-if ! listcontains "meson cmake cmake-make configure ninja make autotools manual" "${PKG_TOOLCHAIN}"; then
-  die "$(print_color "CLR_ERROR" "ERROR:") unknown toolchain ${PKG_TOOLCHAIN}"
-fi
-build_msg "CLR_TOOLCHAIN" "TOOLCHAIN" "${PKG_TOOLCHAIN}${_auto_toolchain}"
-
-# setup toolchain
-setup_toolchain ${TARGET} ${PKG_TOOLCHAIN}
+setup_toolchain ${TARGET}
 
 # configure install directory
 if [ "${TARGET}" = "target" ]; then
@@ -151,7 +124,7 @@ TARGET_CONFIGURE_OPTS="--host=${TARGET_NAME} \
                        --localstatedir=/var \
                        --disable-static \
                        --enable-shared \
-                       --enable-silent-rules "
+                       --enable-silent-rules"
 
 TARGET_CMAKE_OPTS="-DCMAKE_TOOLCHAIN_FILE=${CMAKE_CONF} \
                    -DCMAKE_INSTALL_PREFIX=/usr \
@@ -178,7 +151,7 @@ HOST_CONFIGURE_OPTS="--host=${HOST_NAME} \
                      --localstatedir=${TOOLCHAIN}/var \
                      --disable-static \
                      --enable-shared \
-                     --enable-silent-rules "
+                     --enable-silent-rules"
 
 HOST_CMAKE_OPTS="${CMAKE_GENERATOR} \
                  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_CONF} \
@@ -203,6 +176,32 @@ INIT_MESON_OPTS="${TARGET_MESON_OPTS}"
 BOOTSTRAP_CONFIGURE_OPTS="${HOST_CONFIGURE_OPTS}"
 BOOTSTRAP_CMAKE_OPTS="${HOST_CMAKE_OPTS}"
 BOOTSTRAP_MESON_OPTS="${HOST_MESON_OPTS}"
+
+# setup configure scripts
+PKG_CONFIGURE_SCRIPT="${PKG_CONFIGURE_SCRIPT:-${PKG_BUILD}/configure}"
+PKG_CMAKE_SCRIPT="${PKG_CMAKE_SCRIPT:-${PKG_BUILD}/CMakeLists.txt}"
+PKG_MESON_SCRIPT="${PKG_MESON_SCRIPT:-${PKG_BUILD}/meson.build}"
+
+# auto detect toolchain
+_auto_toolchain=""
+if [ -z "${PKG_TOOLCHAIN}" -o "${PKG_TOOLCHAIN}" = "auto" ]; then
+  if [ -f "${PKG_MESON_SCRIPT}" ]; then
+    PKG_TOOLCHAIN="meson"
+  elif [ -f "${PKG_CMAKE_SCRIPT}" ]; then
+    PKG_TOOLCHAIN="cmake"
+  elif [ -f "${PKG_CONFIGURE_SCRIPT}" ]; then
+    PKG_TOOLCHAIN="configure"
+  elif [ -f "${PKG_BUILD}/Makefile" ]; then
+    PKG_TOOLCHAIN="make"
+  else
+    die "Not possible to detect toolchain automatically. Add PKG_TOOLCHAIN= to package.mk"
+  fi
+  _auto_toolchain=" (auto-detect)"
+fi
+if ! listcontains "meson cmake cmake-make configure ninja make autotools manual" "${PKG_TOOLCHAIN}"; then
+  die "$(print_color "CLR_ERROR" "ERROR:") unknown toolchain ${PKG_TOOLCHAIN}"
+fi
+build_msg "CLR_TOOLCHAIN" "TOOLCHAIN" "${PKG_TOOLCHAIN}${_auto_toolchain}"
 
 # make autoreconf
 if [ "${PKG_TOOLCHAIN}" = "autotools" ]; then
@@ -242,22 +241,22 @@ else
   case "${PKG_TOOLCHAIN}:${TARGET}" in
     # meson builds
     "meson:target")
-      create_meson_conf_target ${TARGET} ${MESON_CONF}
+      create_meson_conf ${TARGET} ${MESON_CONF}
       echo "Executing (target): meson ${TARGET_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_TARGET} $(dirname ${PKG_MESON_SCRIPT})" | tr -s " "
       CC="${HOST_CC}" CXX="${HOST_CXX}" meson ${TARGET_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_TARGET} $(dirname ${PKG_MESON_SCRIPT})
       ;;
     "meson:host")
-      create_meson_conf_host ${TARGET} ${MESON_CONF}
+      create_meson_conf ${TARGET} ${MESON_CONF}
       echo "Executing (host): meson ${HOST_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_HOST} $(dirname ${PKG_MESON_SCRIPT})" | tr -s " "
       meson ${HOST_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_HOST} $(dirname ${PKG_MESON_SCRIPT})
       ;;
     "meson:init")
-      create_meson_conf_target ${TARGET} ${MESON_CONF}
+      create_meson_conf ${TARGET} ${MESON_CONF}
       echo "Executing (init): meson ${INIT_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_INIT} $(dirname ${PKG_MESON_SCRIPT})" | tr -s " "
       meson ${INIT_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_INIT} $(dirname ${PKG_MESON_SCRIPT})
       ;;
     "meson:bootstrap")
-      create_meson_conf_host ${TARGET} ${MESON_CONF}
+      create_meson_conf ${TARGET} ${MESON_CONF}
       echo "Executing (bootstrap): meson ${BOOTSTRAP_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_BOOTSTRAP} $(dirname ${PKG_MESON_SCRIPT})" | tr -s " "
       meson ${BOOTSTRAP_MESON_OPTS} --cross-file=${MESON_CONF} ${PKG_MESON_OPTS_BOOTSTRAP} $(dirname ${PKG_MESON_SCRIPT})
       ;;
